### ISSUE TITLE
DEB package installs two different SystemD Pilot icons (one is very blurry)

### ISSUE THREAD

**Issue by cvpsmith** [mfat/systemd-pilot#2]
Installed on Ubuntu 24.10 and it installed two separate icons to the desktop.  Looks like both "systemd-pilot.desktop" and "org.mfat.systemdpilot.desktop" are both being installed to /usr/share/applications.

**Comment by mfat** [comment]
Thanks for reporting @cvpsmith . This will be fixed in the next release.

**Comment by cvpsmith** [comment]
No prob.  Nice software btw!

**Comment by cvpsmith** [comment]
For the record, both of the entries work.  I kept the org.mfat.systemdpilot.desktop entry because it has the better icon. ;)

**Comment by mfat** [comment]
@cvpsmith Thanks. Glad you liked the app.
